name: alcov
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bz2file=0.98=py37h06a4308_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cutadapt=2.6=py37h516909a_0
  - dnaio=0.3=py37h14c3975_1
  - htslib=1.13=h9093b5e_0
  - k8=0.2.5=h9a82719_1
  - krb5=1.19.2=hac12032_0
  - libcurl=7.87.0=h91b91d3_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.52.0=ha637b67_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - minimap2=2.22=h5bf99c6_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1w=h7f8727e_0
  - pigz=2.6=h27cfd23_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.3=h0371630_0
  - readline=7.0=h7b6447c_5
  - samtools=1.13=h8c37831_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.38.4=py37h06a4308_0
  - xopen=0.7.3=py_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - alcov==1.1.33
      - bio==1.6.2
      - biopython==1.81
      - biothings-client==0.3.1
      - charset-normalizer==3.3.2
      - cycler==0.11.0
      - fire==0.6.0
      - fonttools==4.38.0
      - gprofiler-official==1.0.0
      - idna==3.10
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - mygene==3.2.2
      - numpy==1.21.6
      - ortools==9.5.2237
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - platformdirs==4.0.0
      - pooch==1.8.2
      - protobuf==4.24.4
      - pyparsing==3.1.4
      - pysam==0.22.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - six==1.16.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tqdm==4.66.5
      - typing-extensions==4.7.1
      - urllib3==2.0.7
prefix: /opt/miniconda3/envs/alcov
